export const BLANK_IMAGE = "/assests/img/blank-placeholder.svg";

const lorem =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";

export function createPlaceholderCaseStudyData({
  title,
  slug,
  color,
  label,
  platform = "Sharetribe",
}) {
  const readableTitle = title.replace(/\.com$/i, "");

  return {
    navLinks: [
      { label: "Overview", id: "overview" },
      { label: "The Challenge", id: "the-challenge" },
      { label: "Tech Stack", id: "tech-stack" },
      { label: "Brand Color & Typo", id: "brand-color-typo" },
      { label: "What We Built", id: "what-we-built" },
      { label: "Technical Highlights", id: "technical-highlights" },
      { label: "Testimonials", id: "testimonials" },
    ],
    heroData: {
      label: label || `Case Study - ${readableTitle}`,
      title: `${readableTitle} placeholder case study headline`,
      subtitle: lorem,
      description: `${lorem}<br/><br/>${lorem}`,
      heroImage: BLANK_IMAGE,
      cardBgColor: color,
    },
    caseStudyData: {
      title: "The Challenge",
      info: [lorem, lorem],
      link: "https://example.com",
      linklabel: `${slug}.example.com`,
      color,
    },
    techStackData: {
      title: "Tech Stack",
      color,
      info: lorem,
      techStack: [
        { layer: "Frontend", technology: "Lorem ipsum" },
        { layer: "Backend / APIs", technology: "Lorem ipsum" },
        { layer: "Platform", technology: platform },
        { layer: "Integrations", technology: "Lorem ipsum" },
        { layer: "Deployment", technology: "Lorem ipsum" },
        { layer: "Design system", technology: "Lorem ipsum" },
      ],
    },
    whatwebuild: [
      {
        id: 1,
        title: "Lorem ipsum feature one",
        description: lorem,
      },
      {
        id: 2,
        title: "Lorem ipsum feature two",
        description: lorem,
      },
      {
        id: 3,
        title: "Lorem ipsum feature three",
        description: lorem,
      },
      {
        id: 4,
        title: "Lorem ipsum feature four",
        description: lorem,
      },
      {
        id: 5,
        title: "Lorem ipsum feature five",
        description: lorem,
      },
      {
        id: 6,
        title: "Lorem ipsum feature six",
        description: lorem,
      },
    ],
    highlightPt: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa.",
    ],
    caseStudyCtaCardData: {
      title: "Ready to Build Your Marketplace?",
      info: "Whether you're scoping a Sharetribe build, a custom platform, or a hybrid, we've shipped 50+ marketplaces across rental, service, product, booking, and B2B verticals. Marketplace builds start at $3,000. Fixed price. 90-day bug-free guarantee.",
      link: "/contact",
      linkLabel: "Book a Free Scoping Call",
      stats: [
        { value: "50+", label: "Marketplaces Delivered" },
        { value: "90 Days", label: "Bug-Free Guarantee" },
        { value: "$3,000", label: "Starting Price" },
      ],
    },
    realStory: {
      avatar: BLANK_IMAGE,
      name: readableTitle,
      founder: "Founder / Team",
      info: lorem,
    },
    themeContent: {
      title: `Modern fonts and dynamic colours of ${readableTitle}`,
      info: lorem,
      colors: [
        {
          id: 1,
          name: "Primary",
          hex: color,
          rgb: "",
          className: "primary",
          large: true,
          textColor: "#FFFFFF",
        },
        {
          id: 2,
          name: "Charcoal",
          hex: "#111827",
          rgb: "",
          className: "charcoal",
          large: false,
          textColor: "#FFFFFF",
        },
        {
          id: 3,
          name: "Off White",
          hex: "#F8FAFC",
          rgb: "",
          className: "offWhite",
          large: false,
          textColor: "#111827",
        },
        {
          id: 4,
          name: "Cloud",
          hex: "#E2E8F0",
          rgb: "",
          className: "cloud",
          large: false,
          textColor: "#111827",
        },
        {
          id: 5,
          name: "Slate",
          hex: "#475569",
          rgb: "",
          className: "slate",
          large: false,
          textColor: "#FFFFFF",
        },
      ],
      typography: {
        bgColor: "#FFFFFF",
        fontFamily: {
          label: "Space Grotesk",
          fontVariable: "--font-space-grotesk",
          color: "#111827",
          primaryFontWeight: "Bold",
        },
        bigText: {
          label: "Aa",
          fontVariable: "--font-space-grotesk",
          color: color,
        },
        secondary: {
          fontFamily: "Inter Tight",
          fontWeight: "Regular",
          fontVariable: "--font-inter-tight",
          color: "#111827",
          charactersColor: "#111827",
          characters: [
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "/",
            "*",
            "!",
            "~",
            "$",
            "%",
            "&",
            "(",
            ")",
            "_",
            "+",
          ],
        },
      },
    },
  };
}
